services:
  YesPlayMusic:
    build:
      context: .
    image: weexy music
    container_name: Weexy Music
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
    restart: always